spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/theSecret
    username: root
    password: "18020809"
  jpa:
    hibernate:
      ddl-auto: create
    sql:
      init:
        mode: always
        platform: postgresql
        schema-locations: classpath:database/initProductsTable.sql
        data-locations: classpath:database/initProductsTable.sql